# to manage the docker multiple containers for the project

version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - SERVER_PORT=8000
    restart: always
  
  frontend:
    build: ./frontend
    ports:
      - "81:80"
    restart: always
  
  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb_data: